import { StyleSheet } from 'react-native';

import { Spacing } from '@/constants/theme';

export const indexStyles = StyleSheet.create({
  screen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.five,
    overflow: 'hidden',
  },
  gradientLayerOne: {
    position: 'absolute',
    width: '120%',
    height: '60%',
    top: '-10%',
    left: '-10%',
    borderRadius: 320,
    backgroundColor: '#2D4B6A',
    opacity: 0.25,
  },
  gradientLayerTwo: {
    position: 'absolute',
    width: '120%',
    height: '60%',
    bottom: '-15%',
    right: '-10%',
    borderRadius: 320,
    backgroundColor: '#7E8FA4',
    opacity: 0.2,
  },
  stack: {
    width: '100%',
    maxWidth: 720,
  },
  glassCard: {
    borderRadius: 28,
    padding: Spacing.five,
    borderWidth: 1,
    shadowColor: '#0B1824',
    shadowOpacity: 0.18,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
  },
  mainCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
    gap: Spacing.three,
  },
  headerRow: {
    gap: Spacing.one,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
  },
  heroCard: {
    width: '100%',
    height: 320,
    borderRadius: 28,
    overflow: 'hidden',
  },
  cardStage: {
    width: '100%',
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
  },
  cardStack: {
    width: '100%',
    height: 992,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  swapCard: {
    position: 'absolute',
    width: '74%',
    height: 666,
    borderRadius: 28,
    opacity: 0.82,
    overflow: 'hidden',
    borderWidth: 1,
    shadowColor: '#08131E',
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  swapPressable: {
    width: '100%',
    height: '100%',
  },
  frontCard: {
    zIndex: 2,
    opacity: 1,
  },
  backCard: {
    zIndex: 1,
  },
  cardHeader: {
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.three,
    gap: 4,
  },
  cardHeaderCompact: {
    paddingTop: Spacing.two,
  },
  cardType: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: '700',
  },
  cardMediaWrap: {
    flex: 1,
    paddingHorizontal: Spacing.three,
    paddingBottom: Spacing.three,
  },
  podcastVisual: {
    marginHorizontal: Spacing.three,
    marginTop: Spacing.two,
    height: 212,
    borderRadius: 24,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  podcastGlow: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 999,
    backgroundColor: '#4B7A61',
    opacity: 0.36,
  },
  podcastVisualLabel: {
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: 1,
  },
  podcastMeta: {
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
    gap: 6,
  },
  podcastSubtitle: {
    fontSize: 15,
    fontWeight: '600',
  },
  podcastDescription: {
    fontSize: 12,
    lineHeight: 18,
  },
  progressDock: {
    position: 'absolute',
    bottom: Spacing.five,
    left: Spacing.five,
    right: Spacing.five,
    alignItems: 'center',
  },
  progressTrack: {
    width: '60%',
    height: 12,
    borderRadius: 999,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
  },
  progressMeta: {
    width: '60%',
    marginTop: Spacing.two,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  metaText: {
    fontSize: 12,
  },
  transportDock: {
    position: 'absolute',
    bottom: Spacing.five + 88,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: Spacing.three,
  },
  transportButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 2,
  },
  transportPrimary: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#08131E',
    shadowOpacity: 0.24,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  transportHint: {
    fontSize: 10,
    fontWeight: '700',
  },
  settingsButton: {
    top: Spacing.four,
    right: Spacing.four,
  },
});
